#!/bin/sh

make distcheck \
    DISTCHECK_CONFIGURE_FLAGS="\
		CXX=mpiCC \
    CXXFLAGS='-g3 -O3 -fno-omit-frame-pointer -DMPICH_IGNORE_CXX_SEEK -DVTK_EXCLUDE_STRSTREAM_HEADERS' \
    --with-paradyn=${HOME}/projects/dawn-sw/sw_beta5/x86_64-unknown-linux2.4 \
    --with-dwarf=/usr/local/tools/libdwarf-2008.10.13 \
    --with-papi=/usr/local/tools/papi \
    --with-python=/usr/gapps/python/chaos_4_x86_64_ib/opt-2.5 \
    --with-python-version=2.5 \
    --with-vtk=/usr/gapps/python/chaos_4_x86_64_ib/opt-2.5" \
    MAKEFLAGS='-j8'
