#!/usr/bin/env python

import os, re

files = os.listdir(".")

tocat = dict()
for file in files:
    match = re.match(r'^((exact-effort-[^-]+-[0-9]+-[0-9]+)-[0-9]+)', file)
    if match:
        part, name = match.groups()
        tocat.setdefault(name, []).append(part)

for key in tocat:
    tocat[key].sort()
    parts = " ".join(tocat[key])

    cat_cmd = "cat %s > %s" % (parts, key)
    os.system(cat_cmd)
    
    rm_cmd  = "rm %s" % parts
    os.system(rm_cmd)
