#!/usr/bin/env ruby
# -*- ruby -*-

exact_filename = /^(exact-\w+-[0-9]+-[0-9]+)-([0-9]+)/

files = Dir.new(".").entries.grep(exact_filename)

tocat = Hash.new {|hash,key| hash[key] = [] }
files.each do |file|
  file.chomp!
  outfile, rank = exact_filename.match(file).captures
  tocat[outfile][rank.to_i] = file
end

tocat.each do |key, list|
  if list.include?(nil)
    puts "Error: Missing files for '#{key}'"
    exit(1)
  end
  cat_cmd = "cat #{list.join(" ")} > #{key}"
  rm_cmd = "rm  #{list.join(" ")}"

  system cat_cmd
  system rm_cmd
end
